### ISSUE TITLE
Automating start and end dates

### ISSUE THREAD

**Issue by showerst** [openstates/people#100]
This is more of a discussion idea for when scrapers slow down than a right-now thing.

An obvious pain-point around this data is term dates. Knowing who's currently serving is the biggest piece, but it would be nice to know when they're up for re-election, and have better dates for historical data as we go forward.

If we know that someone's currently serving in State A District B, then save a few special cases (appointments, special elections), we know the must've been elected in the most recent election, and could likely back into how long the term is. Then on scrape/import we could potentially match this data up and automate spitting out start/end dates.

Do we think this is something that we 1) actually can automate and 2) is worth doing.

Looking at some of the data on ballotpedia [Senate](https://ballotpedia.org/Length_of_terms_of_state_senators) [House](https://ballotpedia.org/Length_of_terms_of_state_representatives) I'm wondering it's worth the effort to try and build out an extra yaml file of metadata, something like:

```
MO:
  term_start: "The second tuesday in january"
  lower_term_limit: 2
  upper_term_limit: 2
  lower_seats:
    - chamber: lower
      district: 6
      ocd_id: ocd-division/country:us/state:mo/sldl:6
      term_type: 2 (as opposed to 4, or 2-2-4)
      terms: 2015, 2017, 2019, 2021, 2023 (this is important in the case of 2-2-4 jurisdictions)
```

Thoughts? I might be over-thinking this a bit.
